services:
  paheko:
    image: docker.io/paheko/paheko:1.3.16
    restart: always
    volumes:
      - ./paheko/config.local.php:/var/www/paheko/config.local.php
      - ./paheko/php.ini:/usr/local/etc/php/php.ini
      - paheko_data:/var/www/paheko/data
      # - /var/www/paheko/data/plugins
    ports:
      - 8080:80
volumes:
  paheko_data:
