/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutWorkflowsRouteImport } from './routes/_layout/workflows'
import { Route as LayoutSourcesRouteImport } from './routes/_layout/sources'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRecordsRouteImport } from './routes/_layout/records'
import { Route as LayoutJobsRouteImport } from './routes/_layout/jobs'
import { Route as LayoutExportersRouteImport } from './routes/_layout/exporters'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutWorkflowsWorkflowIdRouteImport } from './routes/_layout/workflows_.$workflowId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkflowsRoute = LayoutWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSourcesRoute = LayoutSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecordsRoute = LayoutRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutJobsRoute = LayoutJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExportersRoute = LayoutExportersRouteImport.update({
  id: '/exporters',
  path: '/exporters',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWorkflowsWorkflowIdRoute =
  LayoutWorkflowsWorkflowIdRouteImport.update({
    id: '/workflows_/$workflowId',
    path: '/workflows/$workflowId',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/exporters': typeof LayoutExportersRoute
  '/jobs': typeof LayoutJobsRoute
  '/records': typeof LayoutRecordsRoute
  '/settings': typeof LayoutSettingsRoute
  '/sources': typeof LayoutSourcesRoute
  '/workflows': typeof LayoutWorkflowsRoute
  '/': typeof LayoutIndexRoute
  '/workflows/$workflowId': typeof LayoutWorkflowsWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/exporters': typeof LayoutExportersRoute
  '/jobs': typeof LayoutJobsRoute
  '/records': typeof LayoutRecordsRoute
  '/settings': typeof LayoutSettingsRoute
  '/sources': typeof LayoutSourcesRoute
  '/workflows': typeof LayoutWorkflowsRoute
  '/': typeof LayoutIndexRoute
  '/workflows/$workflowId': typeof LayoutWorkflowsWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/exporters': typeof LayoutExportersRoute
  '/_layout/jobs': typeof LayoutJobsRoute
  '/_layout/records': typeof LayoutRecordsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/sources': typeof LayoutSourcesRoute
  '/_layout/workflows': typeof LayoutWorkflowsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/workflows_/$workflowId': typeof LayoutWorkflowsWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/exporters'
    | '/jobs'
    | '/records'
    | '/settings'
    | '/sources'
    | '/workflows'
    | '/'
    | '/workflows/$workflowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/exporters'
    | '/jobs'
    | '/records'
    | '/settings'
    | '/sources'
    | '/workflows'
    | '/'
    | '/workflows/$workflowId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/exporters'
    | '/_layout/jobs'
    | '/_layout/records'
    | '/_layout/settings'
    | '/_layout/sources'
    | '/_layout/workflows'
    | '/_layout/'
    | '/_layout/workflows_/$workflowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/workflows': {
      id: '/_layout/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof LayoutWorkflowsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sources': {
      id: '/_layout/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof LayoutSourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/records': {
      id: '/_layout/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof LayoutRecordsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/jobs': {
      id: '/_layout/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof LayoutJobsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/exporters': {
      id: '/_layout/exporters'
      path: '/exporters'
      fullPath: '/exporters'
      preLoaderRoute: typeof LayoutExportersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/workflows_/$workflowId': {
      id: '/_layout/workflows_/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof LayoutWorkflowsWorkflowIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutExportersRoute: typeof LayoutExportersRoute
  LayoutJobsRoute: typeof LayoutJobsRoute
  LayoutRecordsRoute: typeof LayoutRecordsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSourcesRoute: typeof LayoutSourcesRoute
  LayoutWorkflowsRoute: typeof LayoutWorkflowsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutWorkflowsWorkflowIdRoute: typeof LayoutWorkflowsWorkflowIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutExportersRoute: LayoutExportersRoute,
  LayoutJobsRoute: LayoutJobsRoute,
  LayoutRecordsRoute: LayoutRecordsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSourcesRoute: LayoutSourcesRoute,
  LayoutWorkflowsRoute: LayoutWorkflowsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutWorkflowsWorkflowIdRoute: LayoutWorkflowsWorkflowIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
